# Generated by Django 4.2.16 on 2024-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('PROG', 'In Progress'), ('DONE', 'Done')], default=('TODO', 'Todo'), max_length=5),
        ),
    ]
